# -*- coding: utf-8 -*-
"""Negative_Sel_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104bPF4-8FQfMJtnGtGSIz5QoXOzNQKeP
"""

##General Code file to start with.
import numpy as np
import pandas as pd

def read_input(file):
  ##reads input file
  print("Read File")

def calculate_attachment(Grip,Threshold,cell):
  Calculation = 0
  if (Calculation > 50):
    return True
  return False

def establish_environment(Num_TCells,Concentrations):
    print("\n")

## More to come after reading up on things a bit more

