# -*- coding: utf-8 -*-
"""Negative_Sel_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/104bPF4-8FQfMJtnGtGSIz5QoXOzNQKeP
"""

##General Code file to start with.
import numpy as np
import pandas as pd


#Have to start implementing portions of my project

def read_input(file):
  CellDat = pd.read_csv(filename)

def calculate_attachment(Grip,Threshold,cell):
  Calculation = 0
  if (Calculation > 50):
    return True
  return False

def establish_environment(Num_TCells,Concentrations):
    print("\n")

def Michaelis_Menten(Vmax,S,K_M):
    return Vmax*S/(K_M + S)

## More to come after reading up on things a bit more

#Tests
def read_correctly(Data):
  columns = 0
  while columns != 3:
    print(Data[columns])
    columns += 1

#Main