name: CI

on:
  push:
    branches:
      - main
      - master
      - ci
  pull_request:
    branches:
      - main
      - master
      - ci
env:    # configure environment variables for git commits
  actor: "41898282+github-actions[bot]"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black flake8 # also install black & flake8
        if [ -f requirements.txt ]; then
            pip install -r requirements.txt
        fi
    - name: Configure git  # use the environment variable we set above
      run: |
        git config --local user.email "${actor}@users.noreply.github.com"
        git config --local user.name "$actor"
    - name: Test
      run: |
	pytest .test_Standard_free.py
	pytest .Test_MostP.py
	pytest .Test_find_factors.py
	pytest .test_Entropy_Calculation.py
	pytest .test_Enthalpy_calculation.py
	pytest .Test_Divide_String.py
	pytest .Test_Clean_Lattice.py
	pytest .test_deviations.py
	pytest .test_Calculate_Directions.py
	pytest .Test_Backtracking.py
    - name: Format & lint
      run: |
        black . # first run black, then run flake8
        flake8 --extend-ignore E203 --max-line-length 88 .
